fix: "SCRAM-SHA-1 requires a username" error for mongodb srv config with username
Currently we are setting None to mongodb username and password parameters in FORUM_MONGODB_CLIENT_PARAMETERS.

PyMongo currently throws the following error if the credentials as added to the host parameter as a connection string:

    pymongo.errors.ConfigurationError: SCRAM-SHA-1 requires a username.

This PR fixes this issue by omitting the two parameters completely if the corresponding values are not available.